server:
  port: 8080

film-producer-job:
  frequency: 5000

spring:
  datasource:
    film:
      url: jdbc:postgresql://localhost:5432/bloss
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    review:
      url: jdbc:postgresql://localhost:5432/bloss
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    user:
      url: jdbc:postgresql://localhost:5432/bloss
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    role:
      url: jdbc:postgresql://localhost:5432/bloss
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: guest
    password: guest
    cinema-queue-name: cinema
  main:
    banner-mode: console

hibernate:
  hbm2ddl:
    auto: update
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  temp:
    use_jdbc_metadata_defaults: false
  transaction:
    jta:
      platform: org.hibernate.engine.transaction.jta.platform.internal.AtomikosJtaPlatform

javax:
  persistence:
    transactionType: JTA


jwt:
  token:
    secret: copa
    expired: 7200000
